### ISSUE TITLE
About applying SLPT to videos

### ISSUE THREAD

**Issue by polo5** [Jiahao-UTS/SLPT-master#4]
Hey. Thanks for the interesting work!

When applying SLPT to videos, I find that my keypoints jitter a lot more than in the samples you showed. Did you use filters to make them smoother?

I also noticed that the detector you chose uses a smaller bbox than the WFLW one, which may be a factor in making predictions more uncertain?

Thanks!

**Comment by Jiahao-UTS** [comment]
Hi. I didn't use any filter to make the result smoother. I think the main reason is that the result of face detector is unstable. To achieve the best performance of face detector, the ratio of the input video should be 4:3. You can use other tricks, such as face tracking, to make the result more stable.

**Comment by polo5** [comment]
Awesome. Thanks for the reply:)
